CREATE TABLE RECEPTION(
    E_ID VARCHAR(54) PRIMARY KEY,
    NAME VARCHAR(100),
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR(100),
    REGISTER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DONOR(
    D_ID INT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DNAME VARCHAR(50),
    SEX VARCHAR(10),
    AGE INT(3),
    WEIGHT INT(3),
    ADDRESS VARCHAR(150),
    DISEASE VARCHAR(50),
    DEMAIL VARCHAR(100),
    DONOR_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE BLOODBANK(
    B_GROUP VARCHAR(4) PRIMARY KEY,
    TOTAL_PACKETS INT(4)
);

CREATE TABLE BLOOD(
    B_CODE INT(4) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    D_ID INT(3),
    B_GROUP VARCHAR(4),
    PACKETS INT(2),
    CONSTRAINT FK_1 FOREIGN KEY(D_ID) REFERENCES DONOR(D_ID) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT FK_2 FOREIGN KEY(B_GROUP) REFERENCES BLOODBANK(B_GROUP) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE CONTACT(
    CONTACT_ID INT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    B_GROUP VARCHAR(4),
    C_PACKETS INT(2),
    F_NAME VARCHAR(50),
    ADDRESS VARCHAR(250),
    CONSTRAINT FK_3 FOREIGN KEY(B_GROUP) REFERENCES BLOODBANK(B_GROUP) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE NOTIFICATIONS(
    N_ID INT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NB_GROUP VARCHAR(4),
    N_PACKETS INT(2),
    NF_NAME VARCHAR(50),
    N_ADDRESS VARCHAR(250)
);

-- TRIGGER:
DELIMITER //
CREATE TRIGGER agecheck BEFORE INSERT ON DONOR 
FOR EACH ROW 
BEGIN
    IF NEW.age < 21 THEN
        SET NEW.age = 0;
    END IF;
END //
DELIMITER ;
